# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\"\x15\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\"A\n\x05Reply\x12\x1e\n\x07success\x18\x01 \x01(\x0b\x32\r.SuccessReply\x12\x18\n\x04\x66\x61il\x18\x02 \x01(\x0b\x32\n.FailReply\"\x1d\n\x0cSuccessReply\x12\r\n\x05title\x18\x01 \x01(\t\" \n\tFailReply\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t2%\n\x07Library\x12\x1a\n\x04\x42ook\x12\x08.Request\x1a\x06.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=17
  _globals['_REQUEST']._serialized_end=38
  _globals['_REPLY']._serialized_start=40
  _globals['_REPLY']._serialized_end=105
  _globals['_SUCCESSREPLY']._serialized_start=107
  _globals['_SUCCESSREPLY']._serialized_end=136
  _globals['_FAILREPLY']._serialized_start=138
  _globals['_FAILREPLY']._serialized_end=170
  _globals['_LIBRARY']._serialized_start=172
  _globals['_LIBRARY']._serialized_end=209
# @@protoc_insertion_point(module_scope)
